// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbWCweM2wXZXTxayVGM4S-Y2M59lvTJPo',
    appId: '1:195653373656:web:97ecc97d092ec471e451ad',
    messagingSenderId: '195653373656',
    projectId: 'find-my-bus-49f53',
    authDomain: 'find-my-bus-49f53.firebaseapp.com',
    storageBucket: 'find-my-bus-49f53.firebasestorage.app',
    measurementId: 'G-QKL34NWZT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSqikeFgr0mViFhfnfw7gCgNKE96OE1ig',
    appId: '1:195653373656:android:809f3a6f7073ba06e451ad',
    messagingSenderId: '195653373656',
    projectId: 'find-my-bus-49f53',
    storageBucket: 'find-my-bus-49f53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbjyWzBtxADyJLmX1Yb1sDjeCMTUNQgYo',
    appId: '1:195653373656:ios:d1ac3507c72fae0ae451ad',
    messagingSenderId: '195653373656',
    projectId: 'find-my-bus-49f53',
    storageBucket: 'find-my-bus-49f53.firebasestorage.app',
    iosBundleId: 'com.example.bustrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbjyWzBtxADyJLmX1Yb1sDjeCMTUNQgYo',
    appId: '1:195653373656:ios:d1ac3507c72fae0ae451ad',
    messagingSenderId: '195653373656',
    projectId: 'find-my-bus-49f53',
    storageBucket: 'find-my-bus-49f53.firebasestorage.app',
    iosBundleId: 'com.example.bustrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbWCweM2wXZXTxayVGM4S-Y2M59lvTJPo',
    appId: '1:195653373656:web:5c0a45c951ab22e9e451ad',
    messagingSenderId: '195653373656',
    projectId: 'find-my-bus-49f53',
    authDomain: 'find-my-bus-49f53.firebaseapp.com',
    storageBucket: 'find-my-bus-49f53.firebasestorage.app',
    measurementId: 'G-0KY98LHD82',
  );
}
